In [1]:
print("Hello, World!")

Hello, World!

In [2]:
import pandas as pd

In [6]:
df= pd.read_csv("./war_economic_impact_dataset.csv")
df.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes

In [7]:
df.columns

Index(['Conflict_Name', 'Conflict_Type', 'Region', 'Start_Year', 'End_Year',
       'Status', 'Primary_Country', 'Pre_War_Unemployment_%',
       'During_War_Unemployment_%', 'Unemployment_Spike_Percentage_Points',
       'Most_Affected_Sector', 'Youth_Unemployment_Change_%',
       'Pre_War_Poverty_Rate_%', 'During_War_Poverty_Rate_%',
       'Extreme_Poverty_Rate_%', 'Food_Insecurity_Rate_%',
       'Households_Fallen_Into_Poverty_Estimate', 'GDP_Change_%',
       'Inflation_Rate_%', 'Currency_Devaluation_%', 'Cost_of_War_USD',
       'Estimated_Reconstruction_Cost_USD', 'Informal_Economy_Size_Pre_War_%',
       'Informal_Economy_Size_During_War_%', 'Black_Market_Activity_Level',
       'Primary_Black_Market_Goods', 'Currency_Black_Market_Rate_Gap_%',
       'War_Profiteering_Documented'],
      dtype='object')

In [ ]:
inflation_above80 = df[df["Inflation_Rate_%"] > 80]
inflation_above80

In [22]:
df= df.fillna(0)
df.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes

In [24]:
top_3_reconstruction_costs = df.sort_values(by="Estimated_Reconstruction_Cost_USD", ascending=False).head(3)
top_3_reconstruction_costs

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
28592,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,9.33,18.52,9.19,...,58.29,42.59,499778735797,1997801970081,30.66,40.63,High,"fuel, currency, medicine",2.30,Yes
16603,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Israel,8.72,35.76,27.03,...,94.53,112.53,498881612069,1994238428066,23.02,29.15,Moderate,currency,11.42,No
8356,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,10.75,62.73,51.97,...,80.94,144.65,499586861266,1992931801300,19.47,41.54,Moderate,"food, currency",10.16,No

In [26]:
inflation_avg = df["Inflation_Rate_%"].mean()
float_inflation_avg = float(inflation_avg)
float_inflation_avg

69.9459648

In [29]:
df['duration_years'] = df["End_Year"] - df["Start_Year"]
df.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented,duration_years
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No,6
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No,3
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No,15
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No,6
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes,20

In [30]:
avg_duration_years = df["duration_years"].mean()
avg_duration_years

np.float64(9.6386)

In [31]:
ongoing_wars = df[df["End_Year"] == 2026]
ongoing_wars.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented,duration_years
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No,3
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No,15
7,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.13,42.10,33.97,...,114.50,351806460488,847527799087,39.15,90.00,Dominant,"currency, medicine",125.89,No,3
9,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,7.41,32.21,24.80,...,90.86,9277326635,25793126375,16.79,39.66,Dominant,"water, weapons",3.49,No,15
12,Russia-Ukraine War,Interstate War,Europe,2022,2026,Ongoing,Ukraine,9.58,23.14,13.56,...,50.13,184490185726,399053363761,17.32,51.12,High,"weapons, currency, water",196.55,Yes,4

In [33]:
df1 = df.groupby("Region")["duration_years"].mean()
df1

Region
Africa         16.077212
East Asia       6.000000
Europe          5.006200
Middle East     7.563249
South Asia     20.000000
Name: duration_years, dtype: float64